### 단위 행렬이란?
대각선은 모두 1이고 나머지는 모두 0인 행렬
### (3,)과 (3,1)의 차이? 
(3,) : 원소가 3개인 1차원 행렬  
(3,1) : 원소가 3개이고 3행1열로 이루어진 2차원 행렬
### resize와 reshape의 차이?
reshape는 행렬의 모양만 바꾸지만,  
resize는 행렬의 원소 수도 바꿀 수 있다.

In [1]:
import numpy as np

In [2]:
#(1)1~25 사이의 2의 배수 12개로 1차원 배열(a) 생성, 출력
print("(1)")
a=np.arange(2, 25, 2)
print("a=",a)
#(2)a 의 인덱스 2~5의 요소값을 -20으로 수정, 출력 
print("\n(2)")
a[2:6]=[-20]
print("a[2~5]=",a[2:6])
#(3)a의 끝에서 두번째부터 끝가지 요소값을 2배하여 저장, 출력
print("\n(3)")
a[-2:]=a[-2:]*2
print("a[-2:]=", a[-2:])
#(4)1~9사이 임의값 12개로  배열 b 생성, 출력
print("\n(4)")
b=np.random.randint(1, 10, 12)
print("b=",b)
#(5)b 배열을 10배하여 c에 저장
print("\n(5)")
c=b*10
print("c=",c)
#(6)a배열과 b배열을 더하여 d 배열 생성
print("\n(6)")
d=a+b
print("d=",d)
#(7)b 배열의 최대,최소,평균 출력
print("\n(7)")
print("max={}, min={}, mean={}".format(max(b),min(b),b.mean()))
#(8)a에서 b 배열의 평균보다 큰값을 추출 
print("\n(8)")
f=a>b.mean()
print("a에서 b배열의 평균보다 큰값=",a[f])

(1)
a= [ 2  4  6  8 10 12 14 16 18 20 22 24]

(2)
a[2~5]= [-20 -20 -20 -20]

(3)
a[-2:]= [44 48]

(4)
b= [1 1 6 8 2 4 2 3 3 5 4 4]

(5)
c= [10 10 60 80 20 40 20 30 30 50 40 40]

(6)
d= [  3   5 -14 -12 -18 -16  16  19  21  25  48  52]

(7)
max=8, min=1, mean=3.5833333333333335

(8)
a에서 b배열의 평균보다 큰값= [ 4 14 16 18 20 44 48]


In [3]:
#(1)1~25 사이의 2의 배수 12개로 1차원 배열(a) 생성, 출력
print("(1)")
a=np.arange(2, 25, 2)
print("a=",a)
#(2)a를 이용하여  3X4 배열로 변경하여 b생성, 출력
print("\n(2)")
b=a.reshape(3, 4)
print("b=",b)
#(3)a를  2X6 배열로 변경, 출력
print("\n(3)")
a=a.reshape(2, 6)
print("a=",a)
#(4)a를  1행의 모든 값을  추출하여 a1을 만들고, a1의 모든 값을 0으로 변경, a1,a출력
print("\n(4)")
a1=a[1,:].copy()
print("a1=",a1)
a1[0:]=0
print("a1={}\na={}".format(a1,a))
#(5)1~10 사이의 임의의 값으로 3X3 배열 x, y생성, 출력
print("\n(5)")
x=np.random.randint(1, 11, size=(3, 3))
y=np.random.randint(1, 11, size=(3, 3))
print("x={}\ny={}".format(x, y))
#(6)x의 1, 2 행의 모든 열추출, 출력
print("\n(6)")
print("x[1,:]={}\nx[2,:]={}".format(x[1,:],x[2,:]))
#(7)x의 2열의 모든 행 추출, 출력
print("\n(7)")
print("x[:,2]=",x[:,2])
#(8)x의 0,2열의 1,2 행 추출, 출력
print("\n(8)")
print("x[1:3,0]={}\nx[1:3,2]={}".format(x[1:3,0],x[1:3,2]))
#(9)x의 각행의 합, 각 열의 합, 출력
print("\n(9)")
print("x[0,:]sum={}\nx[1,:]sum={}\nx[2,:]sum={}".format(x[0,:].sum(), x[1,:].sum(), x[2,:].sum()))
print("x 각 행의 합=",x.sum(axis=1))
print("x[:,0]sum={}\nx[:,1]sum={}\nx[:,2]sum={}".format(x[:,0].sum(), x[:,1].sum(), x[:,2].sum()))
print("x 각 열의 합=",x.sum(axis=0))
#(10)x의 각행의 최대, 각 열의 최대, 출력
print("\n(10)")
print("x[0,:]max={}\nx[1,:]max={}\nx[2,:]max={}".format(x[0,:].max(), x[1,:].max(), x[2,:].max()))
print("x[:,0]max={}\nx[:,1]max={}\nx[:,2]max={}".format(x[:,0].max(), x[:,1].max(), x[:,2].max()))
#(11)x와 y의 합 결과 출력
print("\n(11)")
print("x+y=",x+y)
#(12)X를 1차원으로 변경하여 x1 생성
x1=x.ravel()
print("x1=",x1)

(1)
a= [ 2  4  6  8 10 12 14 16 18 20 22 24]

(2)
b= [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

(3)
a= [[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]

(4)
a1= [14 16 18 20 22 24]
a1=[0 0 0 0 0 0]
a=[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]

(5)
x=[[4 7 8]
 [4 9 6]
 [9 5 1]]
y=[[ 5  5 10]
 [ 7  6  8]
 [ 3  9 10]]

(6)
x[1,:]=[4 9 6]
x[2,:]=[9 5 1]

(7)
x[:,2]= [8 6 1]

(8)
x[1:3,0]=[4 9]
x[1:3,2]=[6 1]

(9)
x[0,:]sum=19
x[1,:]sum=19
x[2,:]sum=15
x 각 행의 합= [19 19 15]
x[:,0]sum=17
x[:,1]sum=21
x[:,2]sum=15
x 각 열의 합= [17 21 15]

(10)
x[0,:]max=8
x[1,:]max=9
x[2,:]max=9
x[:,0]max=9
x[:,1]max=9
x[:,2]max=8

(11)
x+y= [[ 9 12 18]
 [11 15 14]
 [12 14 11]]
x1= [4 7 8 4 9 6 9 5 1]


In [4]:
#(1) 1~3, 10~30, 100~300 3개의 1차원 배열(a1,a2,a3)을 생성하여 
# 행으로 결합된 y배열 생성
print("\n(1)")
a1=np.arange(1, 4)
a2=np.arange(10, 40, 10)
a3=np.arange(100, 400, 100)
y=np.vstack([a1, a2, a3])
print("y=",y)
#(2) y배열의 0,2 열을 복사하여 y1, 1열을 복사하여 y2 생성
print("\n(2)")
y1=np.hstack([y[:,0].copy(), y[:,2].copy()])
y2=y[:,1].copy()
print("y1={}\ny2={}".format(y1, y2))
#(3) y1, y2를 결합하여 yy배열 생성
print("\n(3)")
yy=np.hstack([y1, y2])
print("yy=",yy)


(1)
y= [[  1   2   3]
 [ 10  20  30]
 [100 200 300]]

(2)
y1=[  1  10 100   3  30 300]
y2=[  2  20 200]

(3)
yy= [  1  10 100   3  30 300   2  20 200]
